using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SpawnPoints : MonoBehaviour
{
    public GameObject[] spawnPoints;
    public GameObject enemyToSpawn;
    public float spawnRate;
    // Start is called before the first frame update
    void Start()
    {
        spawnPoints = GameObject.FindGameObjectsWithTag("SpawnPoints");
        InvokeRepeating("Spawn", 0.1f, spawnRate);
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    void Spawn(){
        Instantiate(enemyToSpawn, spawnPoints[Random.Range(0, spawnPoints.Length)].transform.position, Quaternion.identity);

    }
}
